version: '3'

services:
  api:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - API_NAME=$API_NAME
      - HEADLESS=1
      - USER_AGENT=$USER_AGENT
    ports:
      - $PORT:$PORT
    restart: always
